# Generated by Django 4.0.5 on 2022-06-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='available',
            new_name='in_stock',
        ),
    ]
